#!/bin/bash
 
# check for where the latest version of IDEA is installed
IDEA=`ls -1d /Applications/IntelliJ\ * | tail -n1`
wd=`pwd`
 
# were we given a directory?
if [ -d "$1" ]; then
#  echo "checking for things in the working dir given"
  wd=`ls -1d "$1" | head -n1`
fi
 
# were we given a file?
if [ -f "$1" ]; then
#  echo "opening '$1'"
  open -a "$IDEA" "$1"
else
    # let's check for stuff in our working directory.
    pushd $wd > /dev/null
 
    # does our working dir have an .idea directory?
    if [ -d ".idea" ]; then
#      echo "opening via the .idea dir"
      open -a "$IDEA" .
 
    # is there an IDEA project file?
    elif [ -f *.ipr ]; then
#      echo "opening via the project file"
      open -a "$IDEA" `ls -1d *.ipr | head -n1`
 
    # Is there a pom.xml?
    elif [ -f pom.xml ]; then
      open -a "$IDEA" "pom.xml"

    elif [ -f build.sbt ]; then
      open -a "$IDEA" "build.sbt"
    elif [ -d project/ ]; then
      open -a "$IDEA" "project/"	
    else
      open "$IDEA"
    fi
 
    popd > /dev/null
fi
